/-
Copyright (c) 2026 Ember Research Lab. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aaron Ben-Shalom
-/
import SpectralPhysics.Axioms.Laplacian
import Mathlib.Analysis.Matrix.Spectrum
import Mathlib.LinearAlgebra.UnitaryGroup

/-!
# Axioms/RelativeSpectrum.lean — Connes' relative spectrum, finite-dimensional

The second piece of the self-model map (manuscript `def:self-model-map-axioms-stub`,
2026-09-06): for a spectral triple `(A, H, L)` the *relative spectrum*
`Spec_N(A)` (Connes, "A unitary invariant in Riemannian geometry",
arXiv:0810.2091, Def. 2.5) is the position of the observation algebra `A`
relative to the spectral algebra `N` generated by the eigenprojections of `L` —
concretely, the unitary between the eigenbasis of `L` and a basis diagonalising
`A`, modulo the gauge of each eigenspace.

## What is encoded (finite dimensions, honest scope)

* Carrier `X` finite (matches `RelationalStructure`). `H = ℂ^X`, `A = C(X)` acting
  diagonally; the basis diagonalising `A` is the **labelled** minimal-projection
  basis `δ̂_x = δ_x / √μ(x)`, `x : X`. `L` is a Hermitian matrix in that basis.
* `EigenChart X` = an eigenvalue labelling `label : X → ℝ` together with a
  unitary `C : Matrix X X ℂ` whose column `j` is an eigenvector of eigenvalue
  `label j` written in the `A`-basis (`C x j = ⟨δ̂_x, ψ_j⟩`).
* The **gauge** (`IsGauge`): unitaries `g` with `g i j = 0` whenever
  `label i ≠ label' j`, i.e. block unitaries `∏_λ U(mult λ)` acting on the
  eigenbasis side, composed with label-preserving column permutations. This
  contains all per-eigenvector phases and all `U(mult)` rotations inside a
  degenerate eigenspace. `GaugeEquiv` is proved to be an equivalence relation
  (`gaugeSetoid`) and `RelativeSpectrum X` is the quotient.
* The complete gauge invariant is the family of eigenprojections in the
  `A`-basis, `EigenChart.proj c t = C · 1_{label = t} · C*` (T1 both ways:
  `proj_gaugeEquiv`, `gaugeEquiv_of_proj_eq`). Its diagonal
  `proj t x x = Tr(e_x f_t)` is the manuscript's local spectral measure (the
  "moduli"); its off-diagonal entries are the gauge-invariant phase content.
  So the full quotient is encoded, not only the order-1 moduli.

## What is NOT encoded

* Nothing infinite-dimensional; no meromorphic ζ; no manifold reconstruction
  theorem (Connes' theorem is not formalised — the finite-dimensional
  reconstruction `R ∘ M = id` proved in `SelfRefClosure.lean` is the matrix
  spectral theorem, T1).
* The `A`-side symmetries (permutations of `X`, diagonal phases in `A`) are NOT
  quotiented: the map is on labelled structures over a fixed carrier. Two
  isomorphic relabelled structures therefore have different relative spectra.
  The vacuity tests use a non-isomorphic cospectral pair so nothing rests on this.
* Naturality (clause (ii) of Axiom 3) is not formalised.

## Bridge to Axiom 1/2 objects

`RelationalStructure.laplacianMatrix S` is the matrix of `S.SpectralLaplacian` in
the orthonormal basis `δ̂_x`; it is Hermitian (`laplacianMatrix_isHermitian`, T1)
and represents the Laplacian after the unitary `f ↦ √μ · f`
(`laplacianMatrix_mulVec`, T1).

Dependencies: Axioms/RelationalStructure, Axioms/Laplacian, Mathlib matrix spectral theorem.
-/

open Matrix

noncomputable section

namespace SelfModelMap

variable {X : Type*} [Fintype X] [DecidableEq X]

-- ============================================================================
-- SECTION 1: EIGEN-CHARTS AND THE GAUGE GROUP
-- ============================================================================

/-- An eigen-chart: an eigenvalue labelling of a basis, together with the unitary
`C` whose columns are the (labelled) eigenvectors written in the `A`-basis. -/
structure EigenChart (X : Type*) [Fintype X] [DecidableEq X] where
  /-- `label j` is the eigenvalue attached to column `j`. -/
  label : X → ℝ
  /-- `C x j = ⟨δ̂_x, ψ_j⟩`: the eigenbasis-to-`A`-basis unitary. -/
  C : Matrix X X ℂ
  /-- `C` is unitary. -/
  unitary : C ∈ Matrix.unitaryGroup X ℂ

/-- The gauge of the eigenbasis: a unitary that is block-diagonal with respect to
the eigenvalue labelling (`g i j = 0` unless `label i = label' j`). This is
`∏_λ U(mult λ)` — all per-eigenvector phases and all rotations inside a
degenerate eigenspace — composed with label-preserving relabellings. -/
def IsGauge (label label' : X → ℝ) (g : Matrix X X ℂ) : Prop :=
  g ∈ Matrix.unitaryGroup X ℂ ∧ ∀ i j, label i ≠ label' j → g i j = 0

/-- Two eigen-charts are gauge-equivalent when they differ by a gauge unitary. -/
def GaugeEquiv (c c' : EigenChart X) : Prop :=
  ∃ g, IsGauge c.label c'.label g ∧ c'.C = c.C * g

theorem gaugeEquiv_refl (c : EigenChart X) : GaugeEquiv c c :=
  ⟨1, ⟨one_mem _, fun _ _ h => Matrix.one_apply_ne (fun hij => h (hij ▸ rfl))⟩,
    (Matrix.mul_one _).symm⟩

theorem gaugeEquiv_symm {c c' : EigenChart X} : GaugeEquiv c c' → GaugeEquiv c' c := by
  rintro ⟨g, ⟨hg, hblk⟩, hC⟩
  refine ⟨star g, ⟨Unitary.star_mem hg, fun i j h => ?_⟩, ?_⟩
  · rw [Matrix.star_apply, hblk j i (Ne.symm h), star_zero]
  · rw [hC, Matrix.mul_assoc, Matrix.mem_unitaryGroup_iff.mp hg, Matrix.mul_one]

theorem gaugeEquiv_trans {a b c : EigenChart X} :
    GaugeEquiv a b → GaugeEquiv b c → GaugeEquiv a c := by
  rintro ⟨g, ⟨hg, hblk⟩, hC⟩ ⟨g', ⟨hg', hblk'⟩, hC'⟩
  refine ⟨g * g', ⟨mul_mem hg hg', fun i j h => ?_⟩, ?_⟩
  · rw [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro k _
    by_cases hk : a.label i = b.label k
    · rw [hblk' k j (fun h' => h (hk.trans h')), mul_zero]
    · rw [hblk i k hk, zero_mul]
  · rw [hC', hC, Matrix.mul_assoc]

/-- Gauge equivalence is an equivalence relation on eigen-charts. -/
instance gaugeSetoid : Setoid (EigenChart X) :=
  ⟨GaugeEquiv, ⟨gaugeEquiv_refl, gaugeEquiv_symm, gaugeEquiv_trans⟩⟩

-- ============================================================================
-- SECTION 2: THE COMPLETE GAUGE INVARIANT — EIGENPROJECTIONS IN THE A-BASIS
-- ============================================================================

/-- Diagonal indicator of the eigenvalue `t` under a labelling. -/
def indicator (label : X → ℝ) (t : ℝ) : Matrix X X ℂ :=
  diagonal (fun i => if label i = t then 1 else 0)

/-- The eigenprojection `f_t` of eigenvalue `t`, written in the `A`-basis:
`C · 1_{label = t} · C*`. Its diagonal entry `proj c t x x = Tr(e_x f_t)` is the
local spectral measure of the manuscript. -/
def EigenChart.proj (c : EigenChart X) (t : ℝ) : Matrix X X ℂ :=
  c.C * indicator c.label t * star c.C

theorem gauge_indicator_comm {label label' : X → ℝ} {g : Matrix X X ℂ}
    (hblk : ∀ i j, label i ≠ label' j → g i j = 0) (t : ℝ) :
    g * indicator label' t = indicator label t * g := by
  ext i j
  rw [indicator, indicator, mul_diagonal, diagonal_mul]
  by_cases h : label i = label' j
  · rw [h, mul_comm]
  · rw [hblk i j h, zero_mul, mul_zero]

/-- [T1] The eigenprojection family is gauge-invariant. -/
theorem proj_gaugeEquiv {c c' : EigenChart X} (h : GaugeEquiv c c') : c.proj = c'.proj := by
  obtain ⟨g, ⟨hg, hblk⟩, hC⟩ := h
  funext t
  have hgg : g * star g = 1 := Matrix.mem_unitaryGroup_iff.mp hg
  simp only [EigenChart.proj, hC, Matrix.star_mul]
  calc c.C * indicator c.label t * star c.C
      = c.C * indicator c.label t * (g * star g) * star c.C := by rw [hgg, Matrix.mul_one]
    _ = c.C * (indicator c.label t * g) * star g * star c.C := by simp only [Matrix.mul_assoc]
    _ = c.C * (g * indicator c'.label t) * star g * star c.C := by
        rw [gauge_indicator_comm hblk]
    _ = c.C * g * indicator c'.label t * (star g * star c.C) := by simp only [Matrix.mul_assoc]

/-- [T1] The eigenprojection family separates gauge classes: charts with the same
eigenprojections differ by a gauge unitary (`g = C* C'`). Together with
`proj_gaugeEquiv`, `proj` is a complete invariant of the gauge quotient. -/
theorem gaugeEquiv_of_proj_eq {c c' : EigenChart X} (h : c.proj = c'.proj) : GaugeEquiv c c' := by
  have hCC : star c.C * c.C = 1 := Matrix.mem_unitaryGroup_iff'.mp c.unitary
  have hCC' : star c'.C * c'.C = 1 := Matrix.mem_unitaryGroup_iff'.mp c'.unitary
  refine ⟨star c.C * c'.C,
    ⟨mul_mem (Unitary.star_mem c.unitary) c'.unitary, fun i j hij => ?_⟩, ?_⟩
  · have h1 : (star c.C * (c'.C * indicator c'.label (c'.label j))) i j
        = (star c.C * c'.C) i j := by
      rw [← Matrix.mul_assoc, indicator, mul_diagonal, if_pos rfl, mul_one]
    have h2 : c'.C * indicator c'.label (c'.label j)
        = c.C * indicator c.label (c'.label j) * star c.C * c'.C := by
      have : c'.C * indicator c'.label (c'.label j) = c'.proj (c'.label j) * c'.C := by
        simp only [EigenChart.proj]
        rw [Matrix.mul_assoc, hCC', Matrix.mul_one]
      rw [this, ← h]
      rfl
    have h3 : star c.C * (c.C * indicator c.label (c'.label j) * star c.C * c'.C)
        = indicator c.label (c'.label j) * (star c.C * c'.C) := by
      simp only [← Matrix.mul_assoc]
      rw [hCC, Matrix.one_mul]
    rw [← h1, h2, h3, indicator, diagonal_mul, if_neg hij, zero_mul]
  · rw [← Matrix.mul_assoc, Matrix.mem_unitaryGroup_iff.mp c.unitary, Matrix.one_mul]

-- ============================================================================
-- SECTION 3: THE RELATIVE SPECTRUM = GAUGE QUOTIENT
-- ============================================================================

/-- `Spec_N(A)` in finite dimensions: eigen-charts modulo the eigenbasis gauge. -/
def RelativeSpectrum (X : Type*) [Fintype X] [DecidableEq X] :=
  Quotient (gaugeSetoid (X := X))

/-- The eigenprojection family descends to the quotient. -/
def RelativeSpectrum.proj : RelativeSpectrum X → ℝ → Matrix X X ℂ :=
  Quotient.lift EigenChart.proj (fun _ _ h => proj_gaugeEquiv h)

/-- [T1] The eigenprojection family is a complete invariant of the relative spectrum. -/
theorem RelativeSpectrum.proj_injective :
    Function.Injective (RelativeSpectrum.proj (X := X)) := by
  intro a b h
  induction a using Quotient.ind
  induction b using Quotient.ind
  exact Quotient.sound (gaugeEquiv_of_proj_eq h)

/-- The manuscript's moduli `Tr(e_x f_t)`: the local spectral measure of `x` at
eigenvalue `t`. Gauge-invariant by construction (it is a function on the quotient). -/
def RelativeSpectrum.localMeasure (r : RelativeSpectrum X) (x : X) (t : ℝ) : ℂ :=
  r.proj t x x

end SelfModelMap

-- ============================================================================
-- SECTION 4: BRIDGE — THE LAPLACIAN OF A RELATIONAL STRUCTURE AS A MATRIX
-- ============================================================================

namespace RelationalStructure

variable (S : RelationalStructure)

/-- Matrix of the spectral Laplacian in the orthonormal basis `δ̂_x = δ_x / √μ(x)`
of `L²(X, μ)`:
`L̂_{xy} = δ_{xy} Σ_z |k(x,z)| μ(z) − |k(x,y)| e^{iθ(x,y)} √(μ(x) μ(y))`. -/
def laplacianMatrix : Matrix S.X S.X ℂ := fun x y =>
  (if x = y then ∑ z, S.weightFactor x z * (S.μ z : ℂ) else 0)
    - S.weightFactor x y * S.phaseFactor x y * ((Real.sqrt (S.μ x * S.μ y) : ℝ) : ℂ)

/-- [T1] The Laplacian matrix is Hermitian (from `weightFactor.symm` and
`phaseFactor.hermitian_conj`). -/
theorem laplacianMatrix_isHermitian : (S.laplacianMatrix).IsHermitian := by
  apply Matrix.IsHermitian.ext
  intro x y
  have hw : ‖S.k y x‖ = ‖S.k x y‖ := S.kernelModulus_symm y x
  have hφ : starRingEnd ℂ (S.phaseFactor y x) = S.phaseFactor x y := by
    rw [phaseFactor.hermitian_conj S x y, Complex.conj_conj]
  simp only [laplacianMatrix, weightFactor, Complex.star_def, map_sub, map_mul,
    Complex.conj_ofReal, hφ, hw, mul_comm (S.μ y)]
  by_cases h : x = y
  · subst h
    simp only [if_true, map_sum, map_mul, Complex.conj_ofReal]
  · rw [if_neg h, if_neg (Ne.symm h), map_zero]

/-- [T1] `laplacianMatrix` represents `SpectralLaplacian` after the unitary
`f ↦ √μ · f` from `L²(X, μ)` to `ℂ^X`. -/
theorem laplacianMatrix_mulVec (f : S.X → ℂ) (x : S.X) :
    (S.laplacianMatrix *ᵥ fun y => ((Real.sqrt (S.μ y) : ℝ) : ℂ) * f y) x
      = ((Real.sqrt (S.μ x) : ℝ) : ℂ) * S.SpectralLaplacian f x := by
  have hsq : ∀ y, ((Real.sqrt (S.μ x * S.μ y) : ℝ) : ℂ) * (Real.sqrt (S.μ y) : ℂ)
      = (Real.sqrt (S.μ x) : ℂ) * (S.μ y : ℂ) := by
    intro y
    rw [Real.sqrt_mul (le_of_lt (S.μ_pos x)), Complex.ofReal_mul, mul_assoc,
      ← Complex.ofReal_mul, Real.mul_self_sqrt (le_of_lt (S.μ_pos y))]
  simp only [Matrix.mulVec, dotProduct, laplacianMatrix, SpectralLaplacian, ite_mul, zero_mul,
    sub_mul, mul_sub, Finset.sum_sub_distrib, Finset.sum_ite_eq, Finset.mem_univ, if_true,
    Finset.mul_sum, Finset.sum_mul]
  congr 1
  · refine Finset.sum_congr rfl fun z _ => ?_
    ring
  · refine Finset.sum_congr rfl fun y _ => ?_
    have := hsq y
    calc S.weightFactor x y * S.phaseFactor x y * ((Real.sqrt (S.μ x * S.μ y) : ℝ) : ℂ)
          * ((Real.sqrt (S.μ y) : ℝ) * f y)
        = S.weightFactor x y * S.phaseFactor x y * f y
          * (((Real.sqrt (S.μ x * S.μ y) : ℝ) : ℂ) * (Real.sqrt (S.μ y) : ℂ)) := by ring
      _ = (Real.sqrt (S.μ x) : ℂ)
          * (S.weightFactor x y * (S.phaseFactor x y * f y) * (S.μ y : ℂ)) := by
          rw [this]; ring

end RelationalStructure

end
