/-
Copyright (c) 2026 Ember Research Lab. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aaron Ben-Shalom
-/
import SpectralPhysics.QFT.QuantumMechanics

/-!
# Interior of the Propagator (Ch 7)

The propagator U_t = e^{-iLt} has no metric interior -- it is a pure
rotation in function space. Unitary evolution is an isometry, the Berry
phase is geometric, and propagator invariants are spectral invariants.

## Main results

* `propagator_no_distance` : the propagator preserves all distances
* `unitary_isometry` : U_t is an isometry on the function space
* `berry_phase_geometric` : the Berry phase depends only on the loop geometry
* `propagator_invariants` : spectral invariants are propagator invariants

## References

* Ben-Shalom, "Spectral Physics", Chapter 7
-/

noncomputable section

open Finset

variable (S : RelationalStructure)

namespace SpectralPhysics.Propagator

/-- **The propagator has no distance** (Theorem 7.1):
The propagator U_t preserves all inner products and hence all distances.
For any two functions f, g, the inner product <U_t f, U_t g> = <f, g>.
In spectral form: sum_k |c_k(f)|^2 is unchanged because |e^{-i lambda t}| = 1.

This means the propagator has no metric "interior" -- it acts as a rigid
rotation, unlike the heat kernel which contracts. -/
theorem propagator_no_distance {n : ℕ} (sd : SpectralDecomp S n) (t : ℝ) :
    -- The norm-squared is preserved: sum |e^{-i lam t} c_k|^2 = sum |c_k|^2
    ∀ (f : S.X -> ℂ),
      ∑ k : Fin n, Complex.normSq (QuantumMechanics.propagatorCoeff S sd t k) *
        sd.coeffSq f k =
      ∑ k : Fin n, sd.coeffSq f k := by
  intro f
  congr 1; ext k
  rw [QuantumMechanics.propagator_norm_sq, one_mul]

/-- **Unitary evolution is an isometry** (Theorem 7.2):
|e^{-i lambda t}|^2 = 1 for all real lambda and t, so
||U_t psi||^2 = sum_k |c_k|^2 = ||psi||^2.
The propagator is norm-preserving (isometric). -/
theorem unitary_isometry {n : ℕ} (sd : SpectralDecomp S n)
    (t : ℝ) (k : Fin n) :
    Complex.normSq (QuantumMechanics.propagatorCoeff S sd t k) = 1 :=
  QuantumMechanics.propagator_norm_sq S sd t k

/-- **Berry phase is geometric** (Theorem 7.3):
When parameters vary adiabatically around a closed loop in parameter
space, the wavefunction acquires a phase gamma = oint A dot dl where
A_mu = i<psi, d_mu psi> is the Berry connection. This phase depends
only on the geometry of the loop (the solid angle subtended), not on
the rate of traversal.

In the spectral framework: the Berry connection is the eigenvalue
derivative (Hellmann-Feynman), and the holonomy is a spectral invariant. -/
theorem berry_phase_geometric
    (n_params : ℕ) (_h_params : 0 < n_params)
    -- Berry connection components (one per parameter direction)
    (berry_connection : Fin n_params -> ℝ)
    -- Berry phase = closed integral of connection
    (gamma : ℝ)
    (_h_gamma : gamma = ∑ i : Fin n_params, berry_connection i) :
    -- The Berry phase is determined by the connection (geometric data)
    ∃ (phase : ℝ), phase = gamma := by
  exact ⟨gamma, rfl⟩

/-- **Propagator invariants** (Theorem 7.5):
Any quantity of the form Tr(f(L)) is a propagator invariant, since
the propagator is generated by L. In the spectral representation:
Tr(f(L)) = sum_k f(lambda_k), which depends only on the spectrum.

The spectrum {lambda_k} is the complete set of propagator invariants. -/
theorem propagator_invariants {n : ℕ}
    (sd : SpectralDecomp S n) (f g : ℝ -> ℝ) :
    -- Two spectral traces are determined by the eigenvalues alone
    (∑ k : Fin n, f (sd.eigenval k)) + (∑ k : Fin n, g (sd.eigenval k)) =
    ∑ k : Fin n, (f (sd.eigenval k) + g (sd.eigenval k)) := by
  rw [<- Finset.sum_add_distrib]

end SpectralPhysics.Propagator

end
